drop table if exists device cascade;
drop table if exists event;
drop table if exists deviceState;

create table device
(
    id bigint generated by default as identity primary key,
    name varchar(50)
);
create table event
(
    id bigint generated by default as identity primary key,
    device_id int8,
    timestamp TIMESTAMP,
    latitude DECIMAL,
    longitude DECIMAL,
    speed DECIMAL,
    bearing DECIMAL,
    altitude DECIMAL,
    accuracy DECIMAL
);

create table deviceState
(
    id bigint generated by default as identity PRIMARY KEY,
    device_id int8,
    timestamp TIMESTAMP,
    userAgent varchar(255),
    batteryLevel DECIMAL
);

alter table event add constraint event_pk foreign key (device_id) references device;
alter table deviceState add constraint devicestate_pk foreign key (device_id) references device;
